<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260213113952 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE character (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, character_id INT NOT NULL, name VARCHAR(255) NOT NULL, ability VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE game (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, game_id INT NOT NULL, user_id_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_232B318C9D86650F ON game (user_id_id)');
        $this->addSql('CREATE TABLE game_lore (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, unlocked BOOLEAN NOT NULL, game_id_id INT NOT NULL, lore_id_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D8FBF9354D77E7D8 ON game_lore (game_id_id)');
        $this->addSql('CREATE INDEX IDX_D8FBF935D8CEE43A ON game_lore (lore_id_id)');
        $this->addSql('CREATE TABLE game_upgrades (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, unlocked BOOLEAN NOT NULL, game_id_id INT NOT NULL, upgrade_id_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4D9FAF234D77E7D8 ON game_upgrades (game_id_id)');
        $this->addSql('CREATE INDEX IDX_4D9FAF23853F5573 ON game_upgrades (upgrade_id_id)');
        $this->addSql('CREATE TABLE lore (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, lore_id INT NOT NULL, descrption VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE maestry (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, level INT NOT NULL, game_id_id INT NOT NULL, type_id_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_FBD5CB8B4D77E7D8 ON maestry (game_id_id)');
        $this->addSql('CREATE INDEX IDX_FBD5CB8B714819A0 ON maestry (type_id_id)');
        $this->addSql('CREATE TABLE stats (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, wpm_best INT DEFAULT NULL, wpm_avg DOUBLE PRECISION DEFAULT NULL, wpm_last INT DEFAULT NULL, er_best INT DEFAULT NULL, er_avg DOUBLE PRECISION DEFAULT NULL, er_last INT DEFAULT NULL, total_runs INT NOT NULL, max_level_reached INT NOT NULL, game_id_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_574767AA4D77E7D8 ON stats (game_id_id)');
        $this->addSql('CREATE TABLE type (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type_id VARCHAR(1) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE upgrades (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, upgrade_id INT NOT NULL, name VARCHAR(255) NOT NULL, description VARCHAR(255) NOT NULL, unlock_condition VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, nickname VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, banned BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('CREATE TABLE word (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, word_id VARCHAR(255) NOT NULL, accent BOOLEAN NOT NULL, language VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE word_type (word_id INT NOT NULL, type_id INT NOT NULL, PRIMARY KEY (word_id, type_id))');
        $this->addSql('CREATE INDEX IDX_844B54C4E357438D ON word_type (word_id)');
        $this->addSql('CREATE INDEX IDX_844B54C4C54C8C93 ON word_type (type_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE game ADD CONSTRAINT FK_232B318C9D86650F FOREIGN KEY (user_id_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE game_lore ADD CONSTRAINT FK_D8FBF9354D77E7D8 FOREIGN KEY (game_id_id) REFERENCES game (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE game_lore ADD CONSTRAINT FK_D8FBF935D8CEE43A FOREIGN KEY (lore_id_id) REFERENCES lore (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE game_upgrades ADD CONSTRAINT FK_4D9FAF234D77E7D8 FOREIGN KEY (game_id_id) REFERENCES game (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE game_upgrades ADD CONSTRAINT FK_4D9FAF23853F5573 FOREIGN KEY (upgrade_id_id) REFERENCES upgrades (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE maestry ADD CONSTRAINT FK_FBD5CB8B4D77E7D8 FOREIGN KEY (game_id_id) REFERENCES game (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE maestry ADD CONSTRAINT FK_FBD5CB8B714819A0 FOREIGN KEY (type_id_id) REFERENCES type (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE stats ADD CONSTRAINT FK_574767AA4D77E7D8 FOREIGN KEY (game_id_id) REFERENCES game (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE word_type ADD CONSTRAINT FK_844B54C4E357438D FOREIGN KEY (word_id) REFERENCES word (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE word_type ADD CONSTRAINT FK_844B54C4C54C8C93 FOREIGN KEY (type_id) REFERENCES type (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE game DROP CONSTRAINT FK_232B318C9D86650F');
        $this->addSql('ALTER TABLE game_lore DROP CONSTRAINT FK_D8FBF9354D77E7D8');
        $this->addSql('ALTER TABLE game_lore DROP CONSTRAINT FK_D8FBF935D8CEE43A');
        $this->addSql('ALTER TABLE game_upgrades DROP CONSTRAINT FK_4D9FAF234D77E7D8');
        $this->addSql('ALTER TABLE game_upgrades DROP CONSTRAINT FK_4D9FAF23853F5573');
        $this->addSql('ALTER TABLE maestry DROP CONSTRAINT FK_FBD5CB8B4D77E7D8');
        $this->addSql('ALTER TABLE maestry DROP CONSTRAINT FK_FBD5CB8B714819A0');
        $this->addSql('ALTER TABLE stats DROP CONSTRAINT FK_574767AA4D77E7D8');
        $this->addSql('ALTER TABLE word_type DROP CONSTRAINT FK_844B54C4E357438D');
        $this->addSql('ALTER TABLE word_type DROP CONSTRAINT FK_844B54C4C54C8C93');
        $this->addSql('DROP TABLE character');
        $this->addSql('DROP TABLE game');
        $this->addSql('DROP TABLE game_lore');
        $this->addSql('DROP TABLE game_upgrades');
        $this->addSql('DROP TABLE lore');
        $this->addSql('DROP TABLE maestry');
        $this->addSql('DROP TABLE stats');
        $this->addSql('DROP TABLE type');
        $this->addSql('DROP TABLE upgrades');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE word');
        $this->addSql('DROP TABLE word_type');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
